GET http://localhost:3001/api/blogs

#### add new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "how to test modules",
    "author": "fullStackOpen",
    "url": "fso.com",
    "likes": 96334
}
